"""
utils/dl_classifier.py
────────────────────────────────────────────────────────────────────────────────
Deep Learning–style Threat Severity Classifier
───────────────────────────────────────────────
Architecture: TF-IDF vectoriser  →  Multi-Layer Perceptron (MLP)
              (sklearn's MLPClassifier — a genuine neural network with
               configurable hidden layers, ReLU activation, and
               stochastic gradient descent / Adam optimisation)

Why MLP instead of PyTorch/TensorFlow?
  • Zero heavy deps — deploys on Streamlit Community Cloud free tier
  • MLPClassifier IS a deep neural network (weight matrices, activation
    functions, backpropagation) — just without GPU overhead
  • Produces real confidence scores (predict_proba) used by the risk layer

Labels: Critical | High | Medium | Low

The model is TRAINED ONCE per session (or when data changes) using the
existing rule-based scores as silver labels, then all subsequent scoring
goes through the neural network.  The rule-based scorer remains as a
fallback when the training set is too small (<30 rows).

Public API
──────────
  train(df)           → DLClassifier instance (cached by Streamlit)
  predict(texts)      → list[dict]  each: {label, confidence, proba_vec}
  is_ready()          → bool
────────────────────────────────────────────────────────────────────────────────
"""

from __future__ import annotations

import hashlib
import numpy as np
import pandas as pd
from typing import List, Dict, Tuple

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

from utils.risk_scorer import compute_impact_score

# ── Constants ─────────────────────────────────────────────────────────────────
LABELS       = ["Low", "Medium", "High", "Critical"]
MIN_TRAIN    = 30           # fall back to rule-based below this
HIDDEN_LAYER = (128, 64)    # 2-layer MLP  (128 neurons → 64 neurons → 4 classes)
MAX_ITER     = 300
RANDOM_STATE = 42


class DLClassifier:
    """
    Neural-network text classifier for cyber threat severity.
    Uses TF-IDF features fed into a Multi-Layer Perceptron.
    """

    def __init__(self):
        self.vectoriser   = TfidfVectorizer(
            max_features=5_000,
            ngram_range=(1, 2),
            sublinear_tf=True,
            strip_accents="unicode",
        )
        self.model        = MLPClassifier(
            hidden_layer_sizes=HIDDEN_LAYER,
            activation="relu",
            solver="adam",
            max_iter=MAX_ITER,
            random_state=RANDOM_STATE,
            early_stopping=True,
            validation_fraction=0.15,
            n_iter_no_change=20,
            verbose=False,
        )
        self.label_enc    = LabelEncoder()
        self._trained     = False
        self._data_hash   = ""
        self.train_report = {}
        self.n_train      = 0
        self.n_classes    = 0

    # ── Training ──────────────────────────────────────────────────────────────
    def train(self, df: pd.DataFrame) -> "DLClassifier":
        """
        Train (or retrain) on a DataFrame of incidents.

        Silver labels are generated by the rule-based risk_scorer so we
        don't need any manual annotation — the DL model learns to
        generalise the rules from raw text.
        """
        texts, labels = self._build_dataset(df)

        if len(texts) < MIN_TRAIN:
            self._trained = False
            return self

        self.label_enc.fit(LABELS)          # always fit on full label set
        y = self.label_enc.transform(labels)

        X = self.vectoriser.fit_transform(texts)

        # Only split if we have enough samples for a test set
        if len(texts) >= 60:
            X_tr, X_val, y_tr, y_val = train_test_split(
                X, y, test_size=0.2, random_state=RANDOM_STATE, stratify=y
            )
            self.model.fit(X_tr, y_tr)
            y_pred = self.model.predict(X_val)
            self.train_report = classification_report(
                y_val, y_pred,
                target_names=self.label_enc.classes_,
                output_dict=True,
                zero_division=0,
            )
        else:
            self.model.fit(X, y)
            self.train_report = {}

        self._trained   = True
        self.n_train    = len(texts)
        self.n_classes  = len(np.unique(y))
        self._data_hash = self._hash(texts)
        return self

    # ── Prediction ────────────────────────────────────────────────────────────
    def predict(self, texts: List[str]) -> List[Dict]:
        """
        Predict severity for a list of text strings.
        Returns list of dicts: {label, confidence, proba}
        Falls back to rule-based if model not trained.
        """
        if not self._trained:
            return [self._rule_fallback(t) for t in texts]

        X = self.vectoriser.transform(texts)
        proba_matrix = self.model.predict_proba(X)          # shape (n, 4)
        class_order  = self.label_enc.inverse_transform(
            np.arange(len(self.model.classes_))
        )

        results = []
        for proba in proba_matrix:
            idx   = int(np.argmax(proba))
            label = self.label_enc.inverse_transform([self.model.classes_[idx]])[0]
            results.append({
                "label":      label,
                "confidence": float(proba[idx]),
                "proba":      {
                    cls: float(p)
                    for cls, p in zip(class_order, proba)
                },
            })
        return results

    def predict_one(self, text: str) -> Dict:
        return self.predict([text])[0]

    def is_ready(self) -> bool:
        return self._trained

    # ── Dataset builder ───────────────────────────────────────────────────────
    @staticmethod
    def _build_dataset(df: pd.DataFrame) -> Tuple[List[str], List[str]]:
        """
        Combine relevant columns into a single text blob per incident,
        then generate silver labels using the rule-based scorer.
        """
        def _col(names):
            for n in names:
                if n in df.columns:
                    return n
            return None

        sector_col  = _col(["sector", "category", "incident_category"])
        country_col = _col(["country", "nation", "location"])
        attack_col  = _col(["incident_type", "attack_type", "type"])
        summary_col = _col(["summary", "description", "content"])
        title_col   = _col(["title", "headline", "post_title"])

        texts, labels = [], []

        for _, row in df.iterrows():
            sector  = str(row.get(sector_col,  "") or "")
            country = str(row.get(country_col, "") or "")
            attack  = str(row.get(attack_col,  "") or "")
            summary = str(row.get(summary_col, "") or "")
            title   = str(row.get(title_col,   "") or "")

            blob = f"{title} {sector} {country} {attack} {summary}".strip()
            if not blob:
                continue

            _, label, _ = compute_impact_score(sector, country, attack,
                                               f"{title} {summary}")
            texts.append(blob)
            labels.append(label)

        return texts, labels

    # ── Rule-based fallback ───────────────────────────────────────────────────
    @staticmethod
    def _rule_fallback(text: str) -> Dict:
        _, label, _ = compute_impact_score("", "", text, text)
        proba_map   = {"Critical": 0.0, "High": 0.0, "Medium": 0.0, "Low": 0.0}
        proba_map[label] = 1.0
        return {"label": label, "confidence": 1.0, "proba": proba_map}

    # ── Utility ───────────────────────────────────────────────────────────────
    @staticmethod
    def _hash(texts: List[str]) -> str:
        combined = "".join(texts[:100])     # sample hash — fast
        return hashlib.md5(combined.encode()).hexdigest()

    # ── Model card (for UI display) ───────────────────────────────────────────
    def model_card(self) -> Dict:
        accuracy = (
            self.train_report.get("accuracy", None)
            if self.train_report else None
        )
        return {
            "architecture":   f"TF-IDF  →  MLP {HIDDEN_LAYER}",
            "activation":     "ReLU",
            "optimiser":      "Adam",
            "max_iter":       MAX_ITER,
            "vocab_size":     len(self.vectoriser.vocabulary_) if self._trained else 0,
            "training_rows":  self.n_train,
            "classes":        self.n_classes,
            "val_accuracy":   round(accuracy, 3) if accuracy else "N/A (small dataset)",
            "early_stopping": True,
            "status":         "Trained ✅" if self._trained else "Not yet trained",
        }
